Basic layout of the calculator app
Jolak5/Math-Magicians pull request #2
Opened 2023-03-21 12:33 UTC by Jolak5

In this PR, I created the basic layout of the calculator app. 

I also fixed the linters

2023-03-21 13:16 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @Jolak5 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHflow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-21 13:16 UTC, tresorsawasawa commented on README.md
> +-->
- [ ] For clean code and as mentioned in the template itself, Kindly make sure you remove all the comments and instructions after you have finished to use the template

2023-03-21 13:16 UTC, tresorsawasawa commented on README.md
> +--->
- [ ] To make your documentation more descriptive and professional, Kindly ensure that you customize your `# Getting Started` section with appropriate information related to your project and add all commands needed such as how to `clone your repo`, `access the cloned directory`, `install dependencies`, `run server(usage)`,... I suggest your refer this template to help you.

2023-03-21 13:16 UTC, tresorsawasawa commented on README.md
> +
- [ ] To make your documentation more professional, kindly make sure you use a working link on your `[Live Demo...]` as the current one shows a `404` error page once clicked. If you need more information about deploying a react app you can refer this **[link](https://blog.logrocket.com/8-ways-deploy-react-app-free/)** as you will find at least **8 ways** on how to deploy a react app online.

2023-03-22 08:35 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @Jolak5,

✔️ Good documentation

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-22 08:55 UTC, closed without merging